# Site settings
author: Michelle Ranly
title: From Michelle
header-img: img/home-bg.png
email: meranly8@gmail.com
copyright_name: Michelle Ranly
description: > # this means to ignore newlines until "baseurl:"
  Blog posts written by me
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  meranly8

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
